meta_product_name: "Cursed planner"
meta_title: "Cursed planner"
meta_description: "We offer you an unique planning simulation experience with AI powered tools"
meta_image: "thesis_schedule.jpg" # should exist in `app/assets/images/`

